### ISSUE TITLE
./add-cluster.sh: line 11: cURL: command not found

### ISSUE THREAD

**Issue by IsQiao** [ozbillwang/rancher-in-kind#2]
docker rm -f rancher-for-kind; kind delete cluster kind-for-rancher
./add-cluster.sh: line 11: cURL: command not found
./add-cluster.sh: line 11: cURL: command not found
./add-cluster.sh: line 11: cURL: command not found
./add-cluster.sh: line 11: cURL: command not found
./add-cluster.sh: line 11: cURL: command not found
./add-cluster.sh: line 11: cURL: command not found

**Comment by ozbillwang** [comment]
Seems your system has no command as `cURL`, replace with `curl`

**Comment by ozbillwang** [comment]
Fixed another issue which need privileged Access for Rancher v2.5+

reference:
https://rancher.com/docs/rancher/v2.x/en/installation/other-installation-methods/single-node-docker/#privileged-access-for-rancher-v2-5
