### ISSUE TITLE
Rancher agent state "Pending" for ever

### ISSUE THREAD

**Issue by inigokintana** [ozbillwang/rancher-in-kind#7]
Hello,

It seems Rancher agent state gets "Pending" for ever while importing existing cluster.

In Kind K8S cluster Rancher agent is not able to contact K3S Rancher server in my Ubuntu VM:

kubectl logs -n cattle-system -f cattle-cluster-agent-757958c58d-mwmqz
> INFO: Environment: CATTLE_ADDRESS=10.244.0.5 CATTLE_CA_CHECKSUM=344b6bcaa1e94f7ea98f6e7d7943e8e934633299adb30f6ef8ff8275b94bd28f CATTLE_CLUSTER=true CATTLE_CLUSTER_AGENT_PORT=tcp://10.96.245.97:80 CATTLE_CLUSTER_AGENT_PORT_443_TCP=tcp://10.96.245.97:443 CATTLE_CLUSTER_AGENT_PORT_443_TCP_ADDR=10.96.245.97 CATTLE_CLUSTER_AGENT_PORT_443_TCP_PORT=443 CATTLE_CLUSTER_AGENT_PORT_443_TCP_PROTO=tcp CATTLE_CLUSTER_AGENT_PORT_80_TCP=tcp://10.96.245.97:80 CATTLE_CLUSTER_AGENT_PORT_80_TCP_ADDR=10.96.245.97 CATTLE_CLUSTER_AGENT_PORT_80_TCP_PORT=80 CATTLE_CLUSTER_AGENT_PORT_80_TCP_PROTO=tcp CATTLE_CLUSTER_AGENT_SERVICE_HOST=10.96.245.97 CATTLE_CLUSTER_AGENT_SERVICE_PORT=80 CATTLE_CLUSTER_AGENT_SERVICE_PORT_HTTP=80 CATTLE_CLUSTER_AGENT_SERVICE_PORT_HTTPS_INTERNAL=443 CATTLE_CLUSTER_REGISTRY= CATTLE_INTERNAL_ADDRESS= CATTLE_IS_RKE=false CATTLE_K8S_MANAGED=true CATTLE_NODE_NAME=cattle-cluster-agent-757958c58d-mwmqz CATTLE_SERVER=https://192.168.1.42:36518 CATTLE_SERVER_VERSION=v2.6.2
> INFO: Using resolv.conf: search cattle-system.svc.cluster.local svc.cluster.local cluster.local nameserver 10.96.0.10 options ndots:5
> ERROR: https://192.168.1.42:36518/ping is not accessible (Failed to connect to 192.168.1.42 port 36518: Connection timed out)

I did have to open port 36518 to make it work:

> ufw allow 36518/tcp
> Rule added
> Rule added (v6)

Best regards

**Comment by ozbillwang** [comment]
Thanks, I run the test again today. It is in pending status as well. 

let me take a look

**Comment by ozbillwang** [comment]
I run a test in my mac, still working. 

it is pending for one or two minutes, then active

![image](https://user-images.githubusercontent.com/8954908/148669540-76dddcb7-9195-4e7a-a5ba-34ca3076f2c1.png)

let me run a test in ubuntu

**Comment by inigokintana** [comment]
yes, my environmet was Ubuntu Linux

Thanks

**Comment by ozbillwang** [comment]
I can't run rancher in ubuntu (virtualbox + vagrant)

https://forums.rancher.com/t/cant-start-rancher-with-docker-in-ubuntu-20-04/36673

**Comment by inigokintana** [comment]
Well, my environment works fine as follows, I do not use vagrant,  everything is running fine with your script but but the trick of opening the port I mentioned at the begining

- virtualbox 6.1
- Ubuntu lsb_release -a
> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu 20.04.3 LTS
> Release:	20.04

- Docker
> Client: Docker Engine - Community
>  Version:           20.10.5
>  API version:       1.41
>  Go version:        go1.13.15
>  Git commit:        55c4c88
>  Built:             Tue Mar  2 20:18:05 2021
>  OS/Arch:           linux/amd64
>  Context:           default
>  Experimental:      true
> 
> Server: Docker Engine - Community
>  Engine:
>   Version:          20.10.5
>   API version:      1.41 (minimum version 1.12)
>   Go version:       go1.13.15
>   Git commit:       363e9a8
>   Built:            Tue Mar  2 20:16:00 2021
>   OS/Arch:          linux/amd64
>   Experimental:     false
>  containerd:
>   Version:          1.4.4
>   GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
>  runc:
>   Version:          1.0.0-rc93
>   GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
>  docker-init:
>   Version:          0.19.0
>   GitCommit:        de40ad0
- Run your script  ./rkind.sh create
- .it creates one bridge network for kind cluster and racnher k3s is installed in default bridge network
>  docker ps
> CONTAINER ID   IMAGE                    COMMAND                  CREATED        STATUS          PORTS                                                                                                     NAMES
> 9fb7187520cb   kindest/node:v1.21.1     "/usr/local/bin/entr…"   13 hours ago   Up 35 minutes   0.0.0.0:4502->4502/tcp, 0.0.0.0:8081->8081/tcp, 0.0.0.0:8443-8445->8443-8445/tcp, 0.0.0.0:9443->443/tcp   kind-for-rancher-worker
> dab8fc2b3ac6   kindest/node:v1.21.1     "/usr/local/bin/entr…"   13 hours ago   Up 35 minutes   127.0.0.1:43467->6443/tcp                                                                                 kind-for-rancher-control-plane
> 869ced84530a   rancher/rancher:v2.6.2   "entrypoint.sh"          13 hours ago   Up 35 minutes   0.0.0.0:30439->80/tcp, 0.0.0.0:36298->443/tcp                                                             rancher-for-kind
> 
> docker network ls
> NETWORK ID     NAME      DRIVER    SCOPE
> 1825490dd28c   bridge    bridge    local  ************
> 9184524a1c1b   host      host      local
> 876a3051c7e4   kind      bridge    local    *********
> 19d1ba9895e2   none      null      local

-  **ufw enable 36298/tcp**
- Run the unsecure port thing curl --insecure -sfL https://192.168.1.42:36298/v3/import/stbbglwcp7gdrqx7v9jl9c59btkwmccz8gsk4kxsbk5vwrv4rczpfv_c-ntrh6.yaml | kubectl apply -f -
- see image 1
![image](https://user-images.githubusercontent.com/45978829/148676868-0b90d37c-bbbc-48bc-88f0-6416a925e29f.png)
- see image 2 inside Kind cluster of agent log
![image](https://user-images.githubusercontent.com/45978829/148677101-5282ac78-7c04-4948-8362-2837c9492321.png)


Let me know if I can help

Best regards

**Comment by ozbillwang** [comment]
thanks for the updates @inigokintana 

If you need deal with firewall and ports, you can hard code the ports at

https://github.com/ozbillwang/rancher-in-kind/blob/master/rkind.sh#L10-L11

```
RANCHER_HTTP_HOST_PORT=$[$[RANDOM%9000]+30000]
RANCHER_HTTPS_HOST_PORT=$[$[RANDOM%9000]+30000]
```

replace to any ports your prefer. Such as 

```
RANCHER_HTTP_HOST_PORT="31000"
RANCHER_HTTPS_HOST_PORT="31001"
```

**Comment by inigokintana** [comment]
Nice to know.

Thank you @ozbillwang for your nice support and script to install Rancher + Kind cluster

Closing the issue
