### ISSUE TITLE
Rancher 2.6.2 only working with K8S

### ISSUE THREAD

**Issue by inigokintana** [ozbillwang/rancher-in-kind#8]
Hello again,

Not really your bug BIll but letting you known Rancher client/agent 2.6 works only with K8S 1.21 on the kind-for-runcher K8S side, please see https://stackoverflow.com/questions/69452080/k3s-cluster-is-pending-in-rancher-dashboard/69661969#69661969

Just modified  your script rkind.sh for kind to use a specific K8s 1.21.10 version and everything works https://stackoverflow.com/questions/56046451/use-kind-to-install-different-kubernetes-version

rkind.sh - line 192
  kind create cluster --name ${KIND_CLUSTER_NAME} --config kind.yaml --image "kindest/node:v1.21.10"

Best regards

**Comment by ozbillwang** [comment]
thanks, let me test. 

I can't upgrade the rancher to higer version currently. Its API keep changing. So lock the Rancher version. Now seems I need lock the k8s version as well.

**Comment by ozbillwang** [comment]
could you please raise the PR?
